## 强制转换

```js
// Number() 转换成数字

// 数值：转换后还是原来的值
Number(324); // 324

// 字符串：如果可以被解析为数值，则转换为相应的数值
Number("324"); // 324

// 字符串：如果不可以被解析为数值，返回 NaN
Number("324abc"); // NaN

// 空字符串转为0
Number(""); // 0

// 布尔值：true 转成 1，false 转成 0
Number(true); // 1
Number(false); // 0

// undefined：转成 NaN
Number(undefined); // NaN

// null：转成0
Number(null); // 0

// 对象转成数字
Number({ a: 1 }); // NaN
Number([1, 2, 3]); // NaN
// 包含单个数值的数组可以转成数字
Number([5]); // 5
```

```js
// String() 转换成字符串

String(123); // "123"
String("abc"); // "abc"
String(true); // "true"
String(undefined); // "undefined"
String(null); // "null"

// 对象转成字符串
String({ a: 1 }); // "[object Object]"
// 对象是数组，返回该数组的字符串形式
String([1, 2, 3]); // "1,2,3"
```

```js
// Boolean() 转换成布尔值

// 除了以下五个值的转换结果为false，其他的值全部为true
Boolean(undefined); // false
Boolean(null); // false
Boolean(0); // false
Boolean(NaN); // false
Boolean(""); // false

// 所有对象（包括空对象）的转换结果都是true
Boolean({}); // true
Boolean([]); // true
Boolean(new Boolean(false)); // true
```

## 自动转换

```js
// 自动转换为布尔值
// 除了以下五个值，其他都是自动转为true
if (!undefined && !null && !0 && !NaN && !"") {
  console.log("true");
}
// true
```

```js
// 自动转换为字符串
"5" + 1; // '51'
"5" + true; // "5true"
"5" + false; // "5false"
"5" + {}; // "5[object Object]"
"5" + []; // "5"
"5" + function () {}; // "5function (){}"
"5" + undefined; // "5undefined"
"5" + null; // "5null"
```

```js
// 自动转换为数值
"5" - "2"; // 3
"5" * "2"; // 10
true - 1; // 0
false - 1; // -1
"1" - 1; // 0
"5" * []; // 0
false / "5"; // 0
"abc" - 1; // NaN
null + 1; // 1
undefined + 1; // NaN
```

## 错误处理机制

```js
// Error 实例对象
// JavaScript 原生提供Error构造函数，所有抛出的错误都是这个构造函数的实例
var err = new Error("出错了");
err.message; // "出错了"
```

**派生自 Error 的 6 种原生错误类型**

```js
// SyntaxError 对象
// SyntaxError对象是解析代码时发生的语法错误

// 变量名错误
var 1a;
// Uncaught SyntaxError: Invalid or unexpected token
```

```js
// ReferenceError 对象
// ReferenceError对象是引用一个不存在的变量时发生的错误

// 使用一个不存在的变量
unknownVariable;
// Uncaught ReferenceError: unknownVariable is not defined
```

```js
// RangeError 对象
// RangeError对象是一个值超出有效范围时发生的错误

// 数组长度不得为负数
new Array(-1);
// Uncaught RangeError: Invalid array length
```

```js
// TypeError 对象
// TypeError对象是变量或参数不是预期类型时发生的错误

var obj = {};
obj.unknownMethod();
// Uncaught TypeError: obj.unknownMethod is not a function
```

```js
// URIError 对象
// URIError对象是 URI 相关函数的参数不正确时抛出的错误

decodeURI("%2");
// URIError: URI malformed
```

```js
// EvalError 对象
// eval函数没有被正确执行时，会抛出EvalError错误
// 该错误类型已经不再使用，只是为了代码兼容才保留
```

**自定义错误对象**

```js
function UserError(message) {
  this.message = message || "默认信息";
  this.name = "UserError";
}

// 自定义错误对象，继承Error对象
UserError.prototype = new Error();
UserError.prototype.constructor = UserError;

new UserError("这是自定义的错误！");
```

**throw 语句**

```js
// throw 语句的作用是手动中断程序执行，抛出一个错误

// 抛出一个错误
var x = -1;
if (x <= 0) {
  throw new Error("x 必须为正数");
}
// Uncaught Error: x 必须为正数

// 抛出一个字符串
throw "Error！";
// Uncaught Error！

// 抛出一个数值
throw 42;
// Uncaught 42

// 抛出一个布尔值
throw true;
// Uncaught true

// 抛出一个对象
throw {
  toString: function () {
    return "Error!";
  },
};
// Uncaught {toString: ƒ}
```

**try...catch**

```js
// try...catch 结构，允许对错误进行处理
try {
  throw new Error("出错了!");
} catch (e) {
  console.log(e.name + ": " + e.message);
  console.log(e.stack);
}
```

**finally**

```js
// try...catch 结构后的 finally 代码块，表示不管是否出现错误，都必需在最后运行的语句
openFile();
try {
  writeFile(Data);
} catch (e) {
  handleError(e);
} finally {
  closeFile();
}
```
